experiment:
  name: "CAR COLL v1"
  template: "standard_gbm"
  veh_type: "CAR"
  coverage: "coll"

machines:
  PC1:
    conda_env: ""
    paths:
      path_prefix: ""
      input_data_dir: ""
      ep_data_dir: ""
      support_dir: ""
  
  PC2:
    conda_env: "py39_26v1"
    paths:
      path_prefix: "/home/carfax_shared/carfax_codedata_refreshv4/datainout/"
      input_data_dir: "datain/"
      ep_data_dir: "ep_data/"
      support_dir: "Other Support/"
  
  PC3:
    conda_env: "py39_26v1"
    paths:
      path_prefix: "/Users/Mach/dev/aps/data/2024_CX_Cmodel/v2/"
      input_data_dir: ""
      ep_data_dir: "ep_data/"
      support_dir: "Other Support/"
  
  PC4:
    conda_env: ""
    paths:
      path_prefix: ""
      input_data_dir: ""
      ep_data_dir: ""
      support_dir: ""

files:
  input_file_pattern: "selectedcolumns_{veh_type}_trainvaliddata_v2.csv"
  ep_file: "data_ep.csv"
  feature_selection: "feature_selection.csv"
  feature_clipping: "feature_clipping.csv"

model:
  debug: false
  debug_rows: 4000000

xgboost:
  tweedie_p: 1.5
  base_margin_factor: 0.08
  max_depth: 6
  num_round: 100
  min_child_weight: 1000
  subsample: 0.8
  colsample_bytree: 1.0
  alpha: 0.25

columns:
  denom_column: "rc_glm_pred_coll"
  offset_column: "offset_AME_VT_VV_coll"
  
  drop_columns:
    - "Unnamed: 0"
    - "bsst"
    - "rc_glm_pred_bi"
    - "rc_glm_pred_pd"
    - "rc_glm_pred_pip"
    - "rc_glm_pred_med"
    - "rc_glm_pred_um_uim"
    - "rc_glm_pred_tot"
    - "ee_bi"
    - "ee_pd"
    - "ee_pip"
    - "ee_med"
    - "ee_um_uim"
    - "ee_tot"
    - "RolloverRisk"
    - "veh_type_factor_coll"
    - "AME_offset_coll"
    - "coll_primary_VV_offset"

  pass_through_columns:
    - "train"
    - "VIN_Date"
    - "rc_glm_pred_coll"
    - "ee_coll"
    - "incurred_cap_AME_VV_VT_coll"
    - "offset_AME_VT_VV_coll"

  float_precision_columns:
    - "vc_Acceleration_0_to_60"
    - "vc_Bed_Length"
    - "vc_Displacement"
    - "vc_derived_hp_to_density"
    - "vc_derived_hp_to_turn"

additional_blank_list:
  # From production CAR COLL notebook - Round 1.0
  - "vc_Power_Folding_Side_Mirrors"
  - "vc_DVD_Player"
  - "vc_Reverse_Automatic_Emergency_Braking"
  - "vc_Navigation_Touchscreen"
  - "vc_Night_Vision"
  - "vc_Forward_Automatic_Emergency_Braking"
  - "vc_Visual_Forward_Collision_Warning"
  # Final Fit
  - "vc_Automatic_Emergency_Braking"
  - "vc_Audible_Forward_Collision_Warning"
